package br.com.easypark.service.timer.config;

/**
 * This class is generated by the Netbeans IDE, and registers all REST root
 * resources created in the project.
 */
@javax.ws.rs.ApplicationPath("rest")
public class ApplicationConfig extends javax.ws.rs.core.Application {

}
